### ISSUE TITLE
Programmable diagrams.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [ParisNeo/QGraphViz#1]
Is it possible embed a diagram to PyQt5 GUI and change the colour of the edges and nodes dynamically?

**Comment by ParisNeo** [comment]
As for the current version we support edge coloring as well as edge width changing.
Just add those parameters to the creation of your edge:
color="red",width=5

**Comment by Sreerag-ibtl** [comment]
Thank you @ParisNeo

**Comment by ParisNeo** [comment]
You're welcome
