### ISSUE TITLE
Changing Length of Edges

### ISSUE THREAD

**Issue by NeelNarvekar** [ParisNeo/QGraphViz#3]
Currently when I generate a large graph, some nodes fall out of the window. If a node goes out of the window I have no way to access it. Is there anyway to resize the graph as a whole or the length of the edges? I saw a parameter to change the width but not one for length. Or additionally is there a way to have the area the graph is generated in be scrollable? I tried putting the widget in a scrollable area but this didn't do anything.

Thanks

**Comment by ParisNeo** [comment]
For now, internal automatic resizing is not implemented. But there is a trick you can perform to acheive your goal.

You can resize your widget so that every thing is visible and put it inside a scroll area.

**Comment by ParisNeo** [comment]
I'll add an option in the next verison to enable automatic resizing of the widget

**Comment by NeelNarvekar** [comment]
Thank you! That worked great
