### ISSUE TITLE
Keep positioning of nodes in json

### ISSUE THREAD

**Issue by NeelNarvekar** [ParisNeo/QGraphViz#4]
This is more of a feature request than an issue, but it'd be really cool if the positions of the nodes were saved in the json file as well. The dot engine doesn't create the most readable graphs sometimes. So if the user tweaked the graph manually and was able to save and then load in this updated graph later that'd be awesome. I'll take a look into the API and see if I can tweak it to make this work when I have some time. But thought I'd post this up in case you were already thinking about this or had some time to do it.

Thanks again!

**Comment by ParisNeo** [comment]
Yes it is exactly what i was going to do.
The idea is that you can freeze graph positions when you want.
I just need to add afunction freeze that adds pos to the json, then when reloading it, puts the nodes in the places that was set to it.
I'll also add a reset method that gives back control to the dot engine.

I'll try to do this during this week, if I can afford some time :)

**Comment by NeelNarvekar** [comment]
That sounds great, thanks! Looking forward to seeing it

**Comment by ParisNeo** [comment]
The feature is now implemented and added to version 0.0.40.
You can upgrade using pip.
You can directly activate autofreeze by setting auto_freeze parameter of the constructor to True, and the position as well as the size of the node will be saved to the json file and reloaded every time you open the file.

The other way is call freeze function every time you want to freeze the position. You can also call unfreeze to remove the freezing if ever you need to let the dot engine take over the placing of the nodes.

**Comment by NeelNarvekar** [comment]
Works great!
