### ISSUE TITLE
Added Node gets sent far off screen

### ISSUE THREAD

**Issue by NeelNarvekar** [ParisNeo/QGraphViz#6]
Hello again! When I add a node to graph for some reason it gets sent to the far right way off screen. Do you have any idea why this might be happening? I didn't have this issue before, think it started happening when I updated the package. Thank you for all your help!

**Comment by ParisNeo** [comment]
Sorry for being late. I wa quite buzzy those days.
Which version are you using ?
I think I used to have this in a previous version, but I fixed it.
Is autofreeze active ?

**Comment by ParisNeo** [comment]
I've just tried this on the example provided with the code (with and withour autofreeze) and I don't get this problem.

Please notice that as for now, only dot engine is implemented which means that you **can NOT use cyclic graphs**. Otherwize, the engine will not perform as expected.

I am planning on implementing other graph engines.

**Comment by NeelNarvekar** [comment]
Oh ok let me try updating the version I'm using, thank you!
