### ISSUE TITLE
Question About Usage

### ISSUE THREAD

**Issue by BryanSouth** [ParisNeo/QGraphViz#7]
Is there a way to convert a Graphviz object to a QGraphviz object?

**Comment by BryanSouth** [comment]
Now that I've done some more digging through the code here, my question is this: Is there a way to convert my Graphviz object to a QGraphviz object?

**Comment by ParisNeo** [comment]
Well, QGraphViz can read a gv file. So if you export your graph as .gv from graphviz, you should be able to reloadit.

Please notice that QGraphViz is no way near Graphviz as it is still a work in progress and I had no time to deal with all features.
The objective is to have an interactive tool to read and build graphs compatible with graphviz and totally open source that you can include in a pyqt or pyside application.

The code source is completely original and does not copy any content from the original graphviz software which is a way bigger and mature software. So for example, the automatic nodes positioning is not yet well coded and I thing I can do better if I only had enough time. And this year, I am really really buzy and couldn't have time to advance any of my personal projects.

Help is welcomed.
This project is open. You can fork it, add features and do a pull request. As long as you stay in the same direction and do not include malicious code, I'll accept the pull request.

Best regards

**Comment by BryanSouth** [comment]
Thanks!

**Comment by lasa-gwt** [comment]
Hello,
First, congratulation and thanks for this great work !
Is it possible to use oriented edges (forward at least) ?

**Comment by ParisNeo** [comment]
Well, edges do have source and destination. The graph is technically an oriented one. but I still need to make some changes to show an actual arrow instead of a simple line.

**Comment by lasa-gwt** [comment]
Would be great ! Thanks.
