### ISSUE TITLE
Error When Modifying Example

### ISSUE THREAD

**Issue by BryanSouth** [ParisNeo/QGraphViz#8]
I'm modifying the script in the example folder to add a second subgraph as well as add edges between the nodes in the subgraph, and I'm getting the following image. The nodes I add to the second subgraph seem to overwrite the first subgraph nodes, and when applying an edge to the nodes in the original subgraph one is booted out of the subgraph box (N12 should be inside, and Y subgraph should have nodes in it). I've named and labelled everything differently so I'm not sure why its not working. Any help would be greatly appreciated. 

![Capture](https://user-images.githubusercontent.com/47403814/110168859-cc076c80-7dc5-11eb-92e3-af16fa5dcee8.JPG)

Here's a snippet of the code for reference. The main differences are the addition of sub_2, n11 and n12, and adding an edge between n11 and n12. 

`qgv.setStyleSheet("background-color:white;")
qgv.new(Dot(Graph("Main_Graph"), show_subgraphs=show_subgraphs, font = QFont("Arial", 12),margins=[20,20]))
n1 = qgv.addNode(qgv.engine.graph, "Node1", label="N1", fillcolor="red")
n2 = qgv.addNode(qgv.engine.graph, "Node2", label="N2", fillcolor="blue:white:red")
n3 = qgv.addNode(qgv.engine.graph, "Node3", label="N3", shape = "diamond",fillcolor="orange")
n4 = qgv.addNode(qgv.engine.graph, "Node4", label="N4", shape="diamond",fillcolor="white")
n5 = qgv.addNode(qgv.engine.graph, "Node5", label="N5", shape="polygon", fillcolor="red", color="white")
n6 = qgv.addNode(qgv.engine.graph, "Node6", label="N6", shape="triangle", fillcolor="blue:white:red")

sub = qgv.addSubgraph(qgv.engine.graph, "sub graph", qgv.engine.graph.graph_type, label="y", fillcolor="blue:white:red")
n7 = qgv.addNode(sub, "Node7", label="N7")
n8 = qgv.addNode(sub, "Node8", label="N8")

icon_path = os.path.dirname(os.path.abspath(__file__)) + r"\icon\dbicon.png,100,100"
n9 = qgv.addNode(qgv.engine.graph, "Node9", label="N9", shape=icon_path)

icon_path = os.path.dirname(os.path.abspath(__file__)) + r"\icon\cam.png"
n10 = qgv.addNode(qgv.engine.graph, "Node10", label="\n\n\nN10\nTest multilines", shape=icon_path, color="white")

sub_2 = qgv.addSubgraph(qgv.engine.graph, "subgraph2", qgv.engine.graph.graph_type, label="x", fillcolor="blue:white:red")
n11 = qgv.addNode(sub_2, "Node_11", label="N11")
n12 = qgv.addNode(sub_2, "Node_12", label="N12")

qgv.addEdge(n1, n2, {})
qgv.addEdge(n3, n2, {})
qgv.addEdge(n2, n4, {"width":2})
qgv.addEdge(n4, n5, {"width":4})
qgv.addEdge(n4, n6, {"width":5,"color":"red"})
qgv.addEdge(n3, n6, {"width":2})
qgv.addEdge(n6, n9, {"width":5,"color":"red"})
qgv.addEdge(n9, n10, {"width":5,"color":"red"})
qgv.addEdge(n11, n12, {})`

**Comment by BryanSouth** [comment]
Interestingly, if I do sub.nodes, the two nodes n7 and n8 are output. So, they are being correctly stored in the subgraph but not displayed. And on top of that, if I add a node using the button in the window, and then drag that added node into the empty subgraph, the node disappears.

**Comment by ParisNeo** [comment]
Hi, Sorry for being late to respond.
I am really buzzy this year and didn't have enough time to deal with reparing this issue.
I did a cuickfix in v 0.55
I added your example with some modifications to default examples so that people can test multiple subgraphs.

Still I need to find some time to fix the automatic nodes positionning system.
This is still a work in progress. An d unfortunately, I rarely have time to update this. 
So, help is welcomed :). You can just fork the project, add the features you want then send a git pull request. I'll merge it as soon as I see it.

**Comment by BryanSouth** [comment]
Awesome, thank you!
